import React from 'react'
import { Checkbox, FormControl, FormLabel, Input, NumberInput, NumberInputField, Select, Stack, Text } from '@chakra-ui/react'
import { useForm } from '~hooks/useForm'; import usePropsSelector from '~hooks/usePropsSelector'
import { normalizeForgeUIIOMonitor } from '~forgeui/ForgeUIIOMonitor'
import { INSPECTOR_PROPERTY_TEXT_COLOR } from '~components/inspector/controls/FormControl'

export const IOMonitorPanel = () => {
  const { setValue } = useForm()
  const raw = { title:usePropsSelector('title'),displayMode:usePropsSelector('displayMode'),channelCount:usePropsSelector('channelCount'),channels:usePropsSelector('channels'),indicatorSize:usePropsSelector('indicatorSize'),showLabels:usePropsSelector('showLabels'),showStateText:usePropsSelector('showStateText'),showValues:usePropsSelector('showValues'),showTimestamps:usePropsSelector('showTimestamps'),rounded:usePropsSelector('rounded'),shadow:usePropsSelector('shadow'),glassStyle:usePropsSelector('glassStyle'),includeInputs:usePropsSelector('includeInputs'),includeOutputs:usePropsSelector('includeOutputs'),includeFaults:usePropsSelector('includeFaults'),includeDisabled:usePropsSelector('includeDisabled'),simulationMode:usePropsSelector('simulationMode'),generateRuntimeApi:usePropsSelector('generateRuntimeApi'),enableUserEvents:usePropsSelector('enableUserEvents') }
  const model:any = normalizeForgeUIIOMonitor(raw)
  const check=(key:string,label:string)=><Checkbox color={INSPECTOR_PROPERTY_TEXT_COLOR} isChecked={model[key]} onChange={e=>setValue(key,e.target.checked)}>{label}</Checkbox>
  const select=(key:string,label:string,values:Array<string|number>)=><FormControl><FormLabel fontSize="xs">{label}</FormLabel><Select size="sm" value={model[key]} onChange={e=>setValue(key,typeof values[0]==='number'?Number(e.target.value):e.target.value)}>{values.map(v=><option key={v} value={v}>{v}</option>)}</Select></FormControl>
  const updateChannel=(index:number,key:string,value:unknown)=>setValue('channels',model.channels.map((channel:any,i:number)=>i===index?{...channel,[key]:value}:channel))
  return <Stack spacing={3} color={INSPECTOR_PROPERTY_TEXT_COLOR}><Text fontSize="sm" fontWeight="bold">ForgeUI Native IO Monitor</Text><Text fontSize="xs" fontWeight="bold">General</Text><FormControl><FormLabel fontSize="xs">Title</FormLabel><Input size="sm" value={model.title} onChange={e=>setValue('title',e.target.value)}/></FormControl>{select('displayMode','Display mode',['compact-grid','detailed-grid','list'])}{select('channelCount','Channel count',[4,8,16,24,32])}
  <Text fontSize="xs" fontWeight="bold">Channels</Text>{model.channels.map((channel:any,index:number)=><Stack key={channel.id} spacing={1} borderBottom="1px solid" borderColor="whiteAlpha.200" pb={2}><Input size="sm" value={channel.label} onChange={e=>updateChannel(index,'label',e.target.value)}/><Select size="sm" value={channel.type} onChange={e=>updateChannel(index,'type',e.target.value)}>{['digital-input','digital-output','relay','sensor','limit-switch','door','pump','valve','motor','fan','solenoid','alarm','fault','generic'].map(v=><option key={v}>{v}</option>)}</Select><Checkbox isChecked={channel.visible} onChange={e=>updateChannel(index,'visible',e.target.checked)}>Visible</Checkbox><Checkbox isChecked={channel.readOnly} onChange={e=>updateChannel(index,'readOnly',e.target.checked)}>Read only</Checkbox></Stack>)}
  <Text fontSize="xs" fontWeight="bold">Appearance</Text><FormControl><FormLabel fontSize="xs">Indicator size</FormLabel><NumberInput size="sm" min={6} max={32} value={model.indicatorSize} onChange={(_,v)=>setValue('indicatorSize',v)}><NumberInputField/></NumberInput></FormControl>{check('showLabels','Labels')}{check('showStateText','State text')}{check('showValues','Values')}{check('showTimestamps','Timestamps')}{check('rounded','Rounded')}{check('shadow','Shadow')}{check('glassStyle','Glass')}
  <Text fontSize="xs" fontWeight="bold">Filtering</Text>{check('includeInputs','Inputs')}{check('includeOutputs','Outputs')}{check('includeFaults','Faults')}{check('includeDisabled','Disabled')}{select('simulationMode','Browser scenario',['idle','random-inputs','relay-activity','machine-running','fault-state','startup-sequence'])}{check('generateRuntimeApi','Generate Runtime SDK')}{check('enableUserEvents','Generate UserEvents')}</Stack>
}
