import React from 'react'
import { ChakraProvider } from '@chakra-ui/react'
import { fireEvent, render, screen } from '@testing-library/react'
import InteractiveThreePositionTogglePreview, { stateFromThreePositionClientX } from './InteractiveThreePositionTogglePreview'

it('maps screen coordinates to all three local hit zones at any control position',()=>{expect(stateFromThreePositionClientX(10,0,90)).toBe('left');expect(stateFromThreePositionClientX(345,300,90)).toBe('center');expect(stateFromThreePositionClientX(980,900,90)).toBe('right');expect(stateFromThreePositionClientX(899,900,90)).toBeUndefined();expect(stateFromThreePositionClientX(990,900,90)).toBeUndefined()})

it('shows the zone guide only when the designer requests it',()=>{const {rerender}=render(<ChakraProvider><InteractiveThreePositionTogglePreview width={90} height={30} state="center"/></ChakraProvider>);expect(screen.queryByTestId('three-position-zone-overlay')).not.toBeInTheDocument();rerender(<ChakraProvider><InteractiveThreePositionTogglePreview width={90} height={30} state="center" showZoneOverlay/></ChakraProvider>);expect(screen.getByTestId('three-position-zone-overlay')).toHaveTextContent('LEFTCENTERRIGHT')})
it('persists the selected preview state through direct callbacks',()=>{let state:'left'|'center'|'right'='center';const onStateChange=jest.fn(next=>{state=next});render(<ChakraProvider><InteractiveThreePositionTogglePreview width={90} height={30} state={state} onStateChange={onStateChange}/></ChakraProvider>);const preview=screen.getByTestId('three-position-preview');jest.spyOn(preview,'getBoundingClientRect').mockReturnValue({left:0,width:90,right:90,top:0,bottom:30,height:30,x:0,y:0,toJSON:()=>({})});fireEvent.click(preview,{clientX:5});expect(onStateChange).toHaveBeenCalledWith('left');fireEvent.click(preview,{clientX:45});expect(onStateChange).toHaveBeenCalledWith('center');fireEvent.click(preview,{clientX:85});expect(onStateChange).toHaveBeenCalledWith('right')})
