import React, { useEffect, useState } from 'react'
import { Box, Button, FormControl, FormLabel, Heading, HStack, Input, NumberInput, NumberInputField, Select, SimpleGrid, Text, VStack } from '@chakra-ui/react'
import { useSelector } from 'react-redux'
import { getComponents, getSelectedComponent } from '~core/selectors/components'
import useDispatch from '~hooks/useDispatch'
import { useForm } from '~hooks/useForm'
import { findInteractiveAssetReferences, formatAssetReferences } from '~forgeui/ForgeUIReferenceProtection'
import type { ForgeUIUploadedAsset } from '~forgeui/ForgeUIUploadedAssetRegistry'
import { createDefaultInteractiveThreePositionToggleAsset, createInteractiveAssetId, getInteractiveThreePositionComponentProps, registerInteractiveAsset, removeInteractiveAsset, resolveInteractiveThreePositionVisuals, saveInteractiveAssets, updateInteractiveAssetByKind } from './index'
import type { ForgeUIInteractiveThreePositionState, ForgeUIInteractiveThreePositionToggleAsset } from './ForgeUIInteractiveThreePositionToggleAsset'
import InteractiveThreePositionTogglePreview from './InteractiveThreePositionTogglePreview'
import InteractiveAssetAIGenerator from './InteractiveAssetAIGenerator'

type Props = { assets: ForgeUIInteractiveThreePositionToggleAsset[]; uploadedAssets: ForgeUIUploadedAsset[]; isActive: boolean; newRequestVersion: number; onAssetsChanged(): void; onUploadedAssetsChanged(): void; onActivate(): void; onClose(): void; onGeneratingChange(value: boolean): void }

const InteractiveThreePositionToggleDesigner = (props: Props) => {
  const selected = useSelector(getSelectedComponent); const components = useSelector(getComponents); const dispatch = useDispatch(); const { setValue } = useForm()
  const [editingId, setEditingId] = useState<string | null>(null); const [name, setName] = useState('New Interactive Three-Position Toggle Switch'); const [label, setLabel] = useState('Three-Position Toggle'); const [width, setWidth] = useState(96); const [height, setHeight] = useState(36)
  const [leftAssetId, setLeft] = useState<string>(); const [centerAssetId, setCenter] = useState<string>(); const [rightAssetId, setRight] = useState<string>(); const [initialState, setInitial] = useState<ForgeUIInteractiveThreePositionState>('center'); const [previewState, setPreview] = useState<ForgeUIInteractiveThreePositionState>('center')
  const ready = props.uploadedAssets.filter(a => a.exportStatus === 'lvgl_ready' && a.lvgl)
  const reset = () => { setEditingId(null); setName('New Interactive Three-Position Toggle Switch'); setLabel('Three-Position Toggle'); setWidth(96); setHeight(36); setLeft(undefined); setCenter(undefined); setRight(undefined); setInitial('center'); setPreview('center') }
  useEffect(() => { if (props.newRequestVersion) reset() }, [props.newRequestVersion])
  const edit = (a: ForgeUIInteractiveThreePositionToggleAsset) => { setEditingId(a.id); setName(a.name); setLabel(a.label); setWidth(a.width); setHeight(a.height); setLeft(a.leftAssetId); setCenter(a.centerAssetId); setRight(a.rightAssetId); setInitial(a.initialState); setPreview(a.initialState); props.onActivate() }
  const save = () => { if (!name.trim() || !label.trim() || width <= 0 || height <= 0 || !leftAssetId || !centerAssetId || !rightAssetId) return; const values = { name: name.trim(), label: label.trim(), width, height, leftAssetId, centerAssetId, rightAssetId, initialState }; if (editingId) updateInteractiveAssetByKind(editingId, 'threePositionToggle', values); else registerInteractiveAsset({ ...createDefaultInteractiveThreePositionToggleAsset(createInteractiveAssetId(), values.name), ...values }); saveInteractiveAssets(); props.onAssetsChanged(); reset(); props.onClose() }
  const assign = (a: ForgeUIInteractiveThreePositionToggleAsset) => { if (!selected || selected.type !== 'InteractiveThreePositionToggleSwitch') return; Object.entries(getInteractiveThreePositionComponentProps(a)).forEach(([name, value]) => { setValue(name, value); dispatch.components.updateProps({ id: selected.id, name, value }) }) }
  const remove = (id: string) => { const refs = findInteractiveAssetReferences(id, components); if (refs.length) return window.alert(formatAssetReferences(refs)); removeInteractiveAsset(id); saveInteractiveAssets(); props.onAssetsChanged() }
  const selector = (title: string, value: string | undefined, setter: (v?: string) => void) => <FormControl isRequired><FormLabel fontSize="sm">{title} Image</FormLabel><Select size="sm" value={value || ''} onChange={e => setter(e.target.value || undefined)}><option value="">Select {title} image</option>{ready.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</Select></FormControl>
  const visuals = resolveInteractiveThreePositionVisuals({ ...createDefaultInteractiveThreePositionToggleAsset('preview'), leftAssetId, centerAssetId, rightAssetId }, props.uploadedAssets)
  return <VStack align="stretch" spacing={4}><Heading size="sm">Interactive Three-Position Toggle Switches</Heading><Text color="gray.400" fontSize="sm">Persistent LEFT / CENTER / RIGHT inputs with direct three-zone selection. Use a horizontal rectangular selector or rocker whose moving control clearly aligns with the three preview zones; avoid indicator-lamp artwork. The zone overlay is designer-only.</Text>
    {props.isActive && <Box borderWidth="1px" borderColor="green.400" borderRadius="md" p={5}><VStack align="stretch" spacing={4}><InteractiveAssetAIGenerator selectedAssetKind="threePositionToggle" width={width} height={height} onGenerated={(l,c,r) => { setLeft(l); setCenter(c); setRight(r) }} onGeneratingChange={props.onGeneratingChange} onUploadedAssetsChanged={props.onUploadedAssetsChanged} /><SimpleGrid columns={{base:1,md:2}} spacing={4}><FormControl isRequired><FormLabel>Asset Name</FormLabel><Input value={name} onChange={e=>setName(e.target.value)}/></FormControl><FormControl isRequired><FormLabel>Label</FormLabel><Input value={label} onChange={e=>setLabel(e.target.value)}/></FormControl><NumberInput min={1} value={width} onChange={(_,v)=>Number.isFinite(v)&&setWidth(v)}><NumberInputField/></NumberInput><NumberInput min={1} value={height} onChange={(_,v)=>Number.isFinite(v)&&setHeight(v)}><NumberInputField/></NumberInput>{selector('LEFT',leftAssetId,setLeft)}{selector('CENTER',centerAssetId,setCenter)}{selector('RIGHT',rightAssetId,setRight)}<FormControl><FormLabel>Initial State</FormLabel><Select value={initialState} onChange={e=>{const s=e.target.value as ForgeUIInteractiveThreePositionState;setInitial(s);setPreview(s)}}><option value="left">LEFT</option><option value="center">CENTER</option><option value="right">RIGHT</option></Select></FormControl></SimpleGrid><InteractiveThreePositionTogglePreview {...visuals} width={width} height={height} state={previewState} onStateChange={setPreview} showZoneOverlay/><HStack justify="flex-end"><Button onClick={props.onClose}>Cancel</Button><Button colorScheme="green" onClick={save} isDisabled={!leftAssetId||!centerAssetId||!rightAssetId}>Save</Button></HStack></VStack></Box>}
    {props.assets.map(a => { const v=resolveInteractiveThreePositionVisuals(a,props.uploadedAssets); return <Box key={a.id} borderWidth="1px" p={4}><HStack justify="space-between"><InteractiveThreePositionTogglePreview {...v} width={Math.min(a.width,96)} height={Math.min(a.height,48)} state={a.initialState}/><Box flex="1"><Heading size="xs">{a.name}</Heading><Text fontSize="xs">Initial {a.initialState.toUpperCase()}</Text></Box><Button size="xs" onClick={()=>assign(a)} isDisabled={selected?.type!=='InteractiveThreePositionToggleSwitch'}>Use on Selected</Button><Button size="xs" onClick={()=>edit(a)}>Edit</Button><Button size="xs" colorScheme="red" onClick={()=>remove(a.id)}>Delete</Button></HStack></Box>})}
  </VStack>
}
export default InteractiveThreePositionToggleDesigner
