import fs from 'fs'
import { generateForgeUILvglCode } from './ForgeUILvglExport'
const card=(id:string,props:Record<string,unknown>={}):IComponent=>({id,parent:'root',type:'PowerFlowCard',children:[],props:{x:20,y:30,w:240,h:145,title:'Power Flow',gridVisible:true,gridValue:'1.2 kW',gridFlow:'into-centre',solarVisible:true,solarValue:'2.8 kW',solarFlow:'into-centre',batteryVisible:true,batteryValue:'0.6 kW',batteryFlow:'out-from-centre',loadVisible:true,loadValue:'3.4 kW',activeColour:'#22C55E',inactiveColour:'#64748B',generateRuntimeApi:true,...props}})
const generate=(...items:IComponent[])=>generateForgeUILvglCode({root:{id:'root',parent:'',type:'Box',children:items.map(i=>i.id),props:{w:1024,h:600}},...Object.fromEntries(items.map(i=>[i.id,i]))} as any,'graphite',undefined,{includeThemeTexture:false})
describe('Power Flow Card LVGL export',()=>{
  it('exports default/minimum deterministic geometry with labels, thick connections and no canvas',()=>{const normal=generate(card('power-default')).code; expect(normal).toContain('lv_obj_set_size(fg_power_default_power_flow,240,145);'); expect(normal).toContain('fg_power_default_power_flow_grid_line'); expect(normal).toContain('lv_obj_set_size(fg_power_default_power_flow_grid_line'); expect(normal).not.toContain('lv_canvas_create'); const minimum=generate(card('power-minimum',{w:220,h:128})).code; expect(minimum).toContain('lv_obj_set_size(fg_power_minimum_power_flow,220,128);'); expect(minimum).toContain('lv_label_set_long_mode(fg_power_minimum_power_flow_load_label,LV_LABEL_LONG_DOT);')})
  it('generates seven silent persisted-ID APIs, refreshes immediately and emits zero UserEvents',()=>{const first=card('power-a'); first.componentName='Renamed Power'; const out=generate(first,card('power-b')); ;['Grid_Value','Grid_Flow','Solar_Value','Solar_Flow','Battery_Value','Battery_Flow','Load_Value'].forEach(name=>{expect(out.code).toContain(`FG_Set_Power_A_${name}`); expect(out.code).toContain(`FG_Set_Power_B_${name}`); expect(out.code).toMatch(new RegExp(`void FG_Set_Power_A_${name}\\([^}]+fg_power_a_power_flow_refresh\\(\\); \\}`))}); expect(out.code).not.toContain('FG_Set_Renamed_Power_Grid_Value'); expect(out.userEventContracts.filter(e=>e.name.toLowerCase().includes('power'))).toEqual([])})
  it('encodes none, inward and outward static arrows and hides optional nodes',()=>{const code=generate(card('states',{gridFlow:'none',solarFlow:'out-from-centre',batteryFlow:'into-centre',gridVisible:false})).code; expect(code).toContain('static const char * horizontal[]={"-",LV_SYMBOL_RIGHT,LV_SYMBOL_LEFT}'); expect(code).toContain('static const char * vertical[]={"-",LV_SYMBOL_DOWN,LV_SYMBOL_UP}'); expect(code).toContain('lv_obj_add_flag(fg_states_power_flow_grid_label,LV_OBJ_FLAG_HIDDEN)')})
  it('isolates backing state and SDK namespaces for duplicates',()=>{const out=generate(card('solar-home',{gridValue:'0.6 kW'}),card('battery-discharge',{gridValue:'0 W'})); expect(out.code).toContain('static char fg_solar_home_power_flow_grid_value[25]="0.6 kW"'); expect(out.code).toContain('static char fg_battery_discharge_power_flow_grid_value[25]="0 W"'); expect(out.publicApiDeclarations).toContain('void FG_Set_Solar_Home_Grid_Value(const char * value);'); expect(out.publicApiDeclarations).toContain('void FG_Set_Battery_Discharge_Grid_Value(const char * value);')})
  it('dumps the 1024x600 three-card hardware proof payload',()=>{if(!process.env.FORGEUI_DUMP_POWER_FLOW_CARD_PAYLOAD)return; const out=generate(card('power-solar-home',{title:'SOLAR HOME',x:40,y:100,solarValue:'2.8 kW',gridValue:'0.6 kW',gridFlow:'into-centre',batteryValue:'0.4 kW',batteryFlow:'out-from-centre',loadValue:'3.0 kW'}),card('power-battery-discharge',{title:'BATTERY DISCHARGE',x:300,y:100,solarValue:'0 W',solarFlow:'none',gridValue:'0 W',gridFlow:'none',batteryValue:'1.4 kW',batteryFlow:'into-centre',loadValue:'1.4 kW'}),card('power-grid-export',{title:'GRID EXPORT',x:560,y:100,solarValue:'4.2 kW',solarFlow:'out-from-centre',gridValue:'1.1 kW',gridFlow:'out-from-centre',batteryValue:'0.5 kW',batteryFlow:'out-from-centre',loadValue:'2.6 kW'})); fs.writeFileSync(process.env.FORGEUI_DUMP_POWER_FLOW_CARD_PAYLOAD,JSON.stringify(out))})
})
