export const FORGEUI_POWER_FLOW_CARD_SCHEMA_VERSION=1
export const FORGEUI_POWER_FLOW_MAX_NODES=17
export const FORGEUI_POWER_FLOW_MAX_CONNECTIONS=12
export type ForgeUIPowerFlowState='unknown'|'idle'|'active'|'importing'|'exporting'|'charging'|'discharging'|'standby'|'offline'|'fault'|'disabled'
export type ForgeUIPowerNodeType='solar'|'grid'|'battery'|'generator'|'wind'|'charger'|'inverter'|'house-load'|'critical-load'|'ev-charger'|'motor-load'|'auxiliary-load'|'shore-power'|'external-dc'|'generic-source'|'generic-storage'|'generic-load'
export type ForgeUIPowerDirection='none'|'forward'|'reverse'|'bidirectional'
export const FORGEUI_POWER_NODE_TYPES:readonly ForgeUIPowerNodeType[]=['solar','grid','battery','generator','wind','charger','inverter','house-load','critical-load','ev-charger','motor-load','auxiliary-load','shore-power','external-dc','generic-source','generic-storage','generic-load']
const num=(v:unknown,f:number,min=-Number.MAX_VALUE,max=Number.MAX_VALUE)=>{const n=Number(v);return Math.max(min,Math.min(max,Number.isFinite(n)?n:f))};const bool=(v:unknown,f:boolean)=>typeof v==='boolean'?v:f;const text=(v:unknown,f='',max=64)=>(typeof v==='string'?v.trim():f).slice(0,max);const pick=<T extends string>(v:unknown,a:readonly T[],f:T)=>a.includes(v as T)?v as T:f
export type ForgeUIPowerNode={type:ForgeUIPowerNodeType;label:string;enabled:boolean;online:boolean;faulted:boolean;power:number;direction:ForgeUIPowerDirection;percentage:number;secondary:string;colour:string}
export type ForgeUIPowerConnection={source:ForgeUIPowerNodeType;destination:ForgeUIPowerNodeType;enabled:boolean;direction:ForgeUIPowerDirection;active:boolean;power:number;state:ForgeUIPowerFlowState}
const labels:Record<ForgeUIPowerNodeType,string>={solar:'Solar',grid:'Grid',battery:'Battery',generator:'Generator',wind:'Wind',charger:'Charger',inverter:'Inverter','house-load':'House Load','critical-load':'Critical Load','ev-charger':'EV Charger','motor-load':'Motor Load','auxiliary-load':'Auxiliary Load','shore-power':'Shore Power','external-dc':'External DC','generic-source':'Source','generic-storage':'Storage','generic-load':'Load'}
const defaultEnabled=new Set<ForgeUIPowerNodeType>(['solar','grid','battery','inverter','house-load'])
export const createForgeUIPowerNodes=(p:Record<string,unknown>):ForgeUIPowerNode[]=>FORGEUI_POWER_NODE_TYPES.map(type=>{const key=type.replace(/-([a-z])/g,(_,c)=>c.toUpperCase());return{type,label:text(p[`${key}Label`],labels[type],32),enabled:bool(p[`${key}Enabled`],defaultEnabled.has(type)),online:bool(p[`${key}Online`],true),faulted:bool(p[`${key}Faulted`],false),power:num(p[`${key}Power`],type==='solar'?3200:type==='house-load'?2450:type==='battery'?-500:type==='grid'?-250:0),direction:pick(p[`${key}Direction`],['none','forward','reverse','bidirectional']as const,type==='battery'||type==='grid'?'bidirectional':'forward'),percentage:num(p[`${key}Percentage`],type==='battery'?82:0,0,100),secondary:text(p[`${key}Secondary`],''),colour:text(p[`${key}Colour`],'#22C55E',7)}})
const baseConnections:ForgeUIPowerConnection[]=[['solar','battery'],['solar','house-load'],['battery','house-load'],['grid','house-load'],['grid','battery'],['generator','house-load'],['shore-power','charger'],['charger','battery'],['solar','ev-charger'],['grid','ev-charger'],['battery','critical-load'],['inverter','house-load']].map(([source,destination])=>({source:source as ForgeUIPowerNodeType,destination:destination as ForgeUIPowerNodeType,enabled:['solar:battery','solar:house-load','battery:house-load','grid:house-load','inverter:house-load'].includes(`${source}:${destination}`),direction:'forward',active:true,power:0,state:'active'}))
export const createForgeUIPowerConnections=(p:Record<string,unknown>):ForgeUIPowerConnection[]=>baseConnections.map(c=>{const key=`${c.source}To${c.destination}`.replace(/-([a-z])/g,(_,x)=>x.toUpperCase());return{...c,enabled:bool(p[`${key}Enabled`],c.enabled),active:bool(p[`${key}Active`],c.active),power:num(p[`${key}Power`],0),direction:pick(p[`${key}Direction`],['none','forward','reverse','bidirectional']as const,c.direction),state:pick(p[`${key}State`],['unknown','idle','active','importing','exporting','charging','discharging','standby','offline','fault','disabled']as const,c.state)}})
export const normalizeForgeUIPowerFlowCard=(p:Record<string,unknown>={})=>({schemaVersion:1 as 1,title:text(p.title,'Power Flow'),displayMode:pick(p.displayMode,['compact','standard','system-dashboard']as const,'standard'),topology:pick(p.topology,['solar-home','battery-backup','marine','ev-charging','generic-four-node']as const,'solar-home'),state:pick(p.state,['unknown','idle','active','importing','exporting','charging','discharging','standby','offline','fault','disabled']as const,'active'),totalGeneration:num(p.totalGeneration,3200),totalLoad:num(p.totalLoad,2450),batteryPower:num(p.batteryPower,-500),gridPower:num(p.gridPower,-250),solarPower:num(p.solarPower,3200),generatorPower:num(p.generatorPower,0),evChargerPower:num(p.evChargerPower,0),auxiliaryPower:num(p.auxiliaryPower,0),systemBalance:num(p.systemBalance,0),efficiency:num(p.efficiency,94.8,0,100),losses:num(p.losses,250),energyToday:num(p.energyToday,18.6),statusText:text(p.statusText,'Solar supplying load and charging battery'),lastUpdateText:text(p.lastUpdateText,'Updated now'),nodes:createForgeUIPowerNodes(p),connections:createForgeUIPowerConnections(p),showNodeLabels:bool(p.showNodeLabels,true),showPowerValues:bool(p.showPowerValues,true),showDirections:bool(p.showDirections,true),showEfficiency:bool(p.showEfficiency,true),showEnergyToday:bool(p.showEnergyToday,true),showBalance:bool(p.showBalance,true),showStatus:bool(p.showStatus,true),showLastUpdate:bool(p.showLastUpdate,true),clickable:bool(p.clickable,true),enableControlRequests:bool(p.enableControlRequests,false),rounded:bool(p.rounded,true),shadow:bool(p.shadow,true),glassStyle:bool(p.glassStyle,false),simulationMode:pick(p.simulationMode,['solar-supplying-load','solar-charging-battery','battery-supplying-load','grid-importing','grid-exporting','generator-active','shore-power-charging','ev-charging','system-idle','node-offline','inverter-fault','mixed-source']as const,'solar-supplying-load'),generateRuntimeApi:bool(p.generateRuntimeApi,true),enableUserEvents:bool(p.enableUserEvents,true)})
export type ForgeUIPowerFlowCardModel=ReturnType<typeof normalizeForgeUIPowerFlowCard>
export const simulateForgeUIPowerFlow=(m:ForgeUIPowerFlowCardModel)=>{const x:Record<string,Partial<ForgeUIPowerFlowCardModel>>={'solar-supplying-load':{state:'active',solarPower:3200,totalGeneration:3200,totalLoad:2450,batteryPower:-500,gridPower:-250},'solar-charging-battery':{state:'charging',solarPower:2800,totalLoad:1400,batteryPower:-1400,gridPower:0},'battery-supplying-load':{state:'discharging',solarPower:0,batteryPower:1800,totalLoad:1800,gridPower:0},'grid-importing':{state:'importing',solarPower:0,gridPower:2600,totalLoad:2400,batteryPower:-200},'grid-exporting':{state:'exporting',solarPower:4200,gridPower:-1400,totalLoad:2300,batteryPower:-500},'generator-active':{state:'active',generatorPower:3500,totalGeneration:3500,totalLoad:2800},'shore-power-charging':{topology:'marine',state:'charging',batteryPower:-900,totalLoad:600},'ev-charging':{topology:'ev-charging',evChargerPower:7200,totalLoad:7600,gridPower:5400,solarPower:2200},'system-idle':{state:'idle',solarPower:0,batteryPower:0,gridPower:0,totalGeneration:0,totalLoad:0},'node-offline':{state:'offline',statusText:'Solar node offline'},'inverter-fault':{state:'fault',statusText:'Inverter fault'},'mixed-source':{solarPower:1800,generatorPower:1200,gridPower:500,totalGeneration:3000,totalLoad:3500}};return{...m,...(x[m.simulationMode]||{})}as ForgeUIPowerFlowCardModel}
export const formatForgeUIPower=(watts:number)=>`${watts<0?'-':''}${Math.abs(watts)>=1000?(Math.abs(watts)/1000).toFixed(2)+' kW':Math.abs(watts).toFixed(0)+' W'}`
