export const FORGEUI_BATTERY_CARD_SCHEMA_VERSION = 1
export type ForgeUIBatteryState = 'unknown'|'idle'|'charging'|'discharging'|'full'|'low'|'critical'|'fault'|'disconnected'
const num=(v:unknown,f:number,min=-Number.MAX_VALUE,max=Number.MAX_VALUE)=>{const n=Number(v);return Math.max(min,Math.min(max,Number.isFinite(n)?n:f))}
const bool=(v:unknown,f:boolean)=>typeof v==='boolean'?v:f
const text=(v:unknown,f='',max=64)=>(typeof v==='string'?v.trim():f).slice(0,max)
const state=(v:unknown):ForgeUIBatteryState=>['unknown','idle','charging','discharging','full','low','critical','fault','disconnected'].includes(String(v))?v as ForgeUIBatteryState:'idle'
export const normalizeForgeUIBatteryCard=(props:Record<string,unknown>={})=>({
 schemaVersion:FORGEUI_BATTERY_CARD_SCHEMA_VERSION as 1,title:text(props.title,'Battery Bank',64)||'Battery Bank',state:state(props.state),stateOfCharge:num(props.stateOfCharge,72,0,100),voltage:num(props.voltage,52.4),current:num(props.current,-12.8),power:num(props.power,-671),energyRemaining:num(props.energyRemaining,7.2,0),capacity:num(props.capacity,10,0),temperature:num(props.temperature,28.4),stateOfHealth:num(props.stateOfHealth,96,0,100),estimatedRuntime:num(props.estimatedRuntime,8.5,0),estimatedChargeTime:num(props.estimatedChargeTime,0,0),chargeCycles:Math.round(num(props.chargeCycles,184,0)),cellCount:Math.round(num(props.cellCount,16,1,256)),minimumCellVoltage:num(props.minimumCellVoltage,3.26,0),maximumCellVoltage:num(props.maximumCellVoltage,3.31,0),statusText:text(props.statusText,'System healthy',64),
 showVoltage:bool(props.showVoltage,true),showCurrent:bool(props.showCurrent,true),showPower:bool(props.showPower,true),showEnergyRemaining:bool(props.showEnergyRemaining,true),showCapacity:bool(props.showCapacity,false),showTemperature:bool(props.showTemperature,true),showStateOfHealth:bool(props.showStateOfHealth,true),showEstimatedRuntime:bool(props.showEstimatedRuntime,true),showEstimatedChargeTime:bool(props.showEstimatedChargeTime,false),showChargeCycles:bool(props.showChargeCycles,false),showCellCount:bool(props.showCellCount,false),showCellVoltages:bool(props.showCellVoltages,false),showStatusText:bool(props.showStatusText,true),rounded:bool(props.rounded,true),shadow:bool(props.shadow,true),glassStyle:bool(props.glassStyle,false),showBatteryOutline:bool(props.showBatteryOutline,true),simulationMode:text(props.simulationMode,'discharging',24),generateRuntimeApi:bool(props.generateRuntimeApi,true),enableUserEvents:bool(props.enableUserEvents,true),
})
export type ForgeUIBatteryCardModel=ReturnType<typeof normalizeForgeUIBatteryCard>
export const simulateForgeUIBattery=(model:ForgeUIBatteryCardModel)=>{const modes:any={idle:{state:'idle',stateOfCharge:72,current:0,power:0},charging:{state:'charging',stateOfCharge:64,current:18.2,power:954},discharging:{state:'discharging',stateOfCharge:72,current:-12.8,power:-671},full:{state:'full',stateOfCharge:100,current:0,power:0},low:{state:'low',stateOfCharge:18,current:-9.4,power:-482},critical:{state:'critical',stateOfCharge:6,current:-7.1,power:-358},fault:{state:'fault',stateOfCharge:42,current:0,power:0},disconnected:{state:'disconnected',stateOfCharge:0,current:0,power:0}};return{...model,...(modes[model.simulationMode]||{})} as ForgeUIBatteryCardModel}
