import React from 'react'
import { ChakraProvider } from '@chakra-ui/react'
import { render, screen } from '@testing-library/react'
import { FORGEUI_POWER_FLOW_CARD_DEFAULT_SIZE, FORGEUI_POWER_FLOW_CARD_MIN_SIZE, normalizeForgeUIPowerFlowCard } from './ForgeUIPowerFlowCard'
import { ForgeUIPowerFlowCardPreview } from './preview/ForgeUIPowerFlowCardPreview'
import { FG_PREVIEW_PALETTES } from './preview/forgeThemeMap'
import { renderForgePreview } from './preview/forgePreviewRenderer'
const component=(id:string,props:Record<string,unknown>={}):IComponent=>({id,parent:'root',type:'PowerFlowCard',children:[],props:{w:240,h:145,...props}})
describe('Power Flow Card',()=>{
  it('normalizes versioned defaults, directions, colours and bounded values',()=>{const m=normalizeForgeUIPowerFlowCard({gridValue:'x'.repeat(100),solarFlow:'bad',activeColour:'bad'}); expect(m).toMatchObject({schemaVersion:1,title:'Power Flow',gridFlow:'into-centre',solarFlow:'into-centre',batteryFlow:'out-from-centre',activeColour:'#22C55E'}); expect(m.gridValue).toHaveLength(24); expect(FORGEUI_POWER_FLOW_CARD_DEFAULT_SIZE).toEqual({width:240,height:145}); expect(FORGEUI_POWER_FLOW_CARD_MIN_SIZE).toEqual({width:220,height:128})})
  it.each([['grid-only','into-centre','none','none'],['solar-load','none','into-centre','none'],['solar-charge','none','into-centre','out-from-centre'],['battery-discharge','none','none','into-centre'],['export','out-from-centre','out-from-centre','none'],['idle','none','none','none']])('renders %s as static explicit directions',(_name,gridFlow,solarFlow,batteryFlow)=>{render(<ChakraProvider><ForgeUIPowerFlowCardPreview component={component(String(_name),{gridFlow,solarFlow,batteryFlow})} palette={FG_PREVIEW_PALETTES.graphite}/></ChakraProvider>); expect(screen.getByTestId('power-flow-grid')).toHaveAttribute('data-flow',gridFlow); expect(screen.getByTestId('power-flow-solar')).toHaveAttribute('data-flow',solarFlow); expect(screen.getByTestId('power-flow-battery')).toHaveAttribute('data-flow',batteryFlow)})
  it('honours node visibility and keeps values readable at minimum geometry',()=>{render(<ChakraProvider><ForgeUIPowerFlowCardPreview component={component('min',{w:220,h:128,gridVisible:false,loadValue:'A VERY LONG LOAD POWER VALUE'})} palette={FG_PREVIEW_PALETTES.graphite}/></ChakraProvider>); expect(screen.getByTestId('power-node-grid')).toHaveStyle('visibility: hidden'); expect(screen.getByText('Power Flow')).toBeInTheDocument(); expect(screen.getByText('A VERY LONG LOAD POWER V')).toBeInTheDocument()})
  it('isolates duplicate previews and routes Browser/Live through the canonical renderer',()=>{const a=component('a',{title:'Solar Home'}); const b=component('b',{title:'Battery Discharge'}); const components:any={root:{id:'root',parent:'root',type:'Box',children:['a','b'],props:{w:1024,h:600}},a,b}; const Harness=()=> <>{renderForgePreview({component:components.root,components})}</>; render(<ChakraProvider><Harness/></ChakraProvider>); expect(screen.getAllByTestId('forgeui-power-flow-card')).toHaveLength(2); expect(screen.getByText('Solar Home')).toBeInTheDocument(); expect(screen.getByText('Battery Discharge')).toBeInTheDocument()})
})
