import fs from 'fs'
import { generateForgeUILvglCode } from './ForgeUILvglExport'
const card=(id:string,props:Record<string,unknown>={}):IComponent=>({id,parent:'root',type:'KpiCard',children:[],props:{x:20,y:30,w:240,h:145,title:'Efficiency',value:'87.4',unit:'%',secondaryText:'Target 90%',trendText:'+2.1%',trendState:'up',status:'good',targetText:'',showSecondary:true,showTrend:true,showTarget:false,generateRuntimeApi:true,...props}})
const generate=(...items:IComponent[])=>generateForgeUILvglCode({root:{id:'root',parent:'',type:'Box',children:items.map(item=>item.id),props:{w:1024,h:600}},...Object.fromEntries(items.map(item=>[item.id,item]))} as any,'graphite',undefined,{includeThemeTexture:false})
describe('KPI Card LVGL export',()=>{
  it('exports default/minimum stackable geometry with safe truncation and no canvas',()=>{const normal=generate(card('kpi-default')).code; expect(normal).toContain('lv_obj_set_size(fg_kpi_default_kpi,240,145);'); expect(normal).toContain('lv_obj_set_size(fg_kpi_default_kpi_accent,220,4);'); expect(normal).toContain('lv_label_set_long_mode(fg_kpi_default_kpi_value_label,LV_LABEL_LONG_DOT);'); expect(normal).not.toContain('lv_canvas_create'); const minimum=generate(card('kpi-minimum',{w:220,h:128,value:'AN EXTREMELY LONG TEXTUAL KPI VALUE'})).code; expect(minimum).toContain('lv_obj_set_size(fg_kpi_minimum_kpi,220,128);'); expect(minimum).toContain('lv_obj_set_width(fg_kpi_minimum_kpi_value_label,144);'); expect(minimum).toContain('lv_obj_set_pos(fg_kpi_minimum_kpi_accent,10,120);')})
  it.each(['0','9.8','87.4','999','1248','99999','-12.5'])('preserves generic textual KPI value %s',value=>{const out=generate(card(`kpi-${value.replace(/[^0-9]/g,'x')}`,{value})); expect(out.code).toContain(`="${value}";`); expect(out.code).toContain(`lv_label_set_text(`)})
  it('generates seven silent persisted-ID setters and zero UserEvents',()=>{const first=card('kpi-a'); first.componentName='Renamed KPI'; const out=generate(first,card('kpi-b',{status:'critical'})); ;['Value','Unit','Secondary_Text','Trend_Text','Trend_State','Status','Target_Text'].forEach(name=>{expect(out.code).toContain(`FG_Set_Kpi_A_${name}`); expect(out.code).toContain(`FG_Set_Kpi_B_${name}`)}); expect(out.code).not.toContain('FG_Set_Renamed_KPI_Value'); expect(out.code).toContain('static char fg_kpi_a_kpi_value[49]="87.4";'); expect(out.code).toContain('static char fg_kpi_b_kpi_value[49]="87.4";'); expect(out.userEventContracts.filter(event=>event.name.toLowerCase().includes('kpi'))).toEqual([]); ;['Value','Unit','Secondary_Text','Trend_Text','Trend_State','Status','Target_Text'].forEach(name=>expect(out.code).toMatch(new RegExp(`void FG_Set_Kpi_A_${name}\\([^}]+fg_kpi_a_kpi_refresh\\(\\); \\}`)))})
  it('renders semantic status, trend and target through ordinary LVGL labels',()=>{const code=generate(card('kpi-state',{status:'warning',trendState:'down',showTarget:true,targetText:'Limit 45 C'})).code; expect(code).toContain('static const char * states[]={"NEUTRAL","GOOD","WARNING","CRITICAL"}'); expect(code).toContain('static const char * trends[]={"FLAT","UP","DOWN"}'); expect(code).toContain('lv_label_set_text_fmt(fg_kpi_state_kpi_trend_label,"%s  %s"'); expect(code).toContain('lv_label_set_text(fg_kpi_state_kpi_target_label,fg_kpi_state_kpi_target)')})
  it('can dump a clean three-instance hardware proof payload',()=>{if(!process.env.FORGEUI_DUMP_KPI_CARD_PAYLOAD)return; const out=generate(card('kpi-a',{title:'Efficiency',x:40,y:100,value:'87.4',unit:'%',secondaryText:'Target 90%',trendText:'+2.1%',trendState:'up',status:'good'}),card('kpi-b',{title:'Temperature',x:300,y:100,value:'42.7',unit:'C',secondaryText:'Limit 45 C',trendText:'+0.8 C',trendState:'up',status:'warning'}),card('kpi-c',{title:'Alarm Count',x:560,y:100,value:'12',unit:'',secondaryText:'Active alarms',trendText:'+3',trendState:'up',status:'critical'})); fs.writeFileSync(process.env.FORGEUI_DUMP_KPI_CARD_PAYLOAD,JSON.stringify(out))})
})
