import { generateForgeUILvglCode } from './ForgeUILvglExport'
import { clearInteractiveAssetRegistry, createDefaultInteractiveThreePositionToggleAsset, getInteractiveThreePositionComponentProps, registerInteractiveAsset, validateInteractiveThreePositionToggleAsset } from './interactive'
import { forgeUIAddUploadedAssets, forgeUIClearUploadedAssets, ForgeUIUploadedAsset } from './ForgeUIUploadedAssetRegistry'

const image = (id:string): ForgeUIUploadedAsset => ({id,name:id,type:'image/png',size:1,createdAt:1,browserSrc:id,kind:'uploaded',exportStatus:'lvgl_ready',lvgl:`fg_${id}`,cFile:`assets/uploads/fg_${id}.c`})

describe('Interactive Three-Position Toggle',()=>{
  beforeEach(()=>{clearInteractiveAssetRegistry();forgeUIClearUploadedAssets()})
  it('creates a typed CENTER default and rejects invalid state',()=>{const asset=createDefaultInteractiveThreePositionToggleAsset('mode');expect(asset.initialState).toBe('center');expect(asset.width).toBe(96);expect(()=>validateInteractiveThreePositionToggleAsset({...asset,initialState:'off'})).toThrow(/left, center, or right/)})
  it('propagates assignment dimensions',()=>expect(getInteractiveThreePositionComponentProps({...createDefaultInteractiveThreePositionToggleAsset('mode'),width:120,height:44})).toEqual({interactiveAssetId:'mode',w:'120',h:'44'}))
  it('emits one shared runtime, unique instances, direct zones, enum, setter, and hooks',()=>{
    const left=image('left'),center=image('center'),right=image('right');forgeUIAddUploadedAssets([left,center,right]);const asset={...createDefaultInteractiveThreePositionToggleAsset('mode'),leftAssetId:left.id,centerAssetId:center.id,rightAssetId:right.id};registerInteractiveAsset(asset)
    const components:IComponents={root:{id:'root',parent:'root',type:'Box',props:{},children:['a','b','c']},a:{id:'a',parent:'root',type:'InteractiveThreePositionToggleSwitch',componentName:'ModeSelector',props:{interactiveAssetId:asset.id,x:0,y:20,w:96,h:36},children:[]},b:{id:'b',parent:'root',type:'InteractiveThreePositionToggleSwitch',componentName:'DriveSelector',props:{interactiveAssetId:asset.id,x:300,y:80,w:96,h:36},children:[]},c:{id:'c',parent:'root',type:'InteractiveThreePositionToggleSwitch',componentName:'EdgeSelector',props:{interactiveAssetId:asset.id,x:900,y:140,w:96,h:36},children:[]}}
    const result=generateForgeUILvglCode(components);expect(result.code.match(/} fg_three_way_input_t;/g)).toHaveLength(1);expect(result.code.match(/static fg_three_way_input_t fg_/g)).toHaveLength(3);expect(result.code).toContain('int32_t local_x = point.x - button_coords.x1;');expect(result.code).toContain('local_x < 0 || local_x >= width');expect(result.code).toContain('local_x < width / 3');expect(result.code).toContain('local_x < (width * 2) / 3');expect(result.code).toContain('lv_obj_set_pos(fg_a_three_way.button, 0, 20);');expect(result.code).toContain('lv_obj_set_pos(fg_b_three_way.button, 300, 80);');expect(result.code).toContain('lv_obj_set_pos(fg_c_three_way.button, 900, 140);');expect(result.code).toContain('lv_obj_add_flag(fg_a_three_way.button, LV_OBJ_FLAG_CLICKABLE);');expect(result.code).toContain('lv_obj_clear_flag(fg_a_three_way.image, LV_OBJ_FLAG_CLICKABLE);');expect(result.code).toContain('false);');expect(result.userEventHooks).toEqual(['FG_On_ModeSelector_Changed','FG_On_DriveSelector_Changed','FG_On_EdgeSelector_Changed']);expect(result.assetSources).toEqual(expect.arrayContaining([left.cFile,center.cFile,right.cFile]))
  })
})
