#pragma once

/* Generated by ForgeUI Studio. Exactly one Hardware Example may be active. */
#define FG_HARDWARE_EXAMPLE_SELECTED 2
#define FG_HARDWARE_EXAMPLE_01_ENABLED 0
#define FG_HARDWARE_EXAMPLE_02_ENABLED 1
#define FG_HARDWARE_EXAMPLE_03_ENABLED 0
