/*
 * ForgeUI User Event Hooks
 *
 * LIVE STUDIO FIRMWARE:
 * This file may be regenerated by ForgeUI Studio for physical testing.
 *
 * STANDALONE EXPORT:
 * After manual export to C:\ForgeUI-Exports, the exported copy is
 * developer-owned. Add GPIO, I/O and application logic there.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

void FG_On_GreenButton_Clicked(void);
void FG_On_RedButton_Clicked(void);
void FG_On_Button_Clicked(void);

#ifdef __cplusplus
}
#endif
