/*
 * ForgeUI User Event Hooks
 *
 * LIVE STUDIO FIRMWARE:
 * This file may be regenerated by ForgeUI Studio while designing,
 * building and flashing the internal ESP32-P4 test firmware.
 *
 * STANDALONE EXPORT:
 * After manually exporting a project to C:\ForgeUI-Exports,
 * the exported copy becomes developer-owned.
 *
 * Add GPIO, I/O, hardware actions and application behaviour to
 * the exported project's 95_UserEvents.c file.
 *
 * Do not place permanent product logic in the live Studio firmware copy.
 */

#include "95_UserEvents.h"
#include <stdio.h>

void FG_On_GreenButton_Clicked(void)
{
    printf("[ForgeUI User Event] FG_On_GreenButton_Clicked\n");
}

void FG_On_RedButton_Clicked(void)
{
    printf("[ForgeUI User Event] FG_On_RedButton_Clicked\n");
}
