export type MenuItem = {
  children?: MenuItems
  soon?: boolean
  rootParentType?: ComponentType
}

type MenuItems = Partial<
  {
    [k in ComponentType]: MenuItem
  }
>

export const menuItems: MenuItems = {
  Accordion: {
    children: {
      Accordion: {},
      AccordionItem: {},
      AccordionButton: {},
      AccordionPanel: {},
      AccordionIcon: {},
    },
  },
  Alert: {
    children: {
      Alert: {},
      AlertDescription: {},
      AlertIcon: {},
      AlertTitle: {},
    },
  },
  AspectRatio: {},
  AvatarGroup: {
    rootParentType: 'Avatar',
  },
  Avatar: {},
  AvatarBadge: {
    rootParentType: 'Avatar',
  },
  Badge: {},
  Box: {},
  Breadcrumb: {
    children: {
      BreadcrumbItem: {},
      BreadcrumbLink: {},
    },
  },
  Button: {},
  InteractiveButton: {},
  InteractiveLight: {},
  InteractiveStatusIndicator: {},
  InteractiveToggleSwitch: {},
  InteractiveThreePositionToggleSwitch: {},
  Center: {},
  Container: {},
  Checkbox: {},
  CircularProgress: {},
  CloseButton: {},
  Code: {},
  Divider: {},
  Flex: {},
  FormControl: {
    children: {
      FormControl: {},
      FormLabel: {},
      FormHelperText: {},
      FormErrorMessage: {},
    },
  },
  Grid: {},
  Heading: {},
  Clock: {},
  WiFi: {},
  Highlight: {},
  Icon: {},
  IconButton: {},
  Span: {},
  Image: {},
  Input: {},
  InputGroup: {
    rootParentType: 'Input',
    children: {
      InputGroup: {},
      Input: {},
      InputLeftAddon: {},
      InputRightAddon: {},
      InputRightElement: {},
      InputLeftElement: {},
    },
  },
  Link: {},
  List: {
    children: {
      List: {},
      ListItem: {},
    },
  },
  Kbd: {},
  NumberInput: {},
  Progress: {},
  Arc: {},
  Bar: {},
  Led: {},
  AnimImage: {},
  ButtonMatrix: {},
  Calendar: {},
  Canvas: {},
  Chart: {},
  QRCode: {},
  ImageButton: {},
  Keyboard: {},
  Line: {},
  Lottie: { soon: true },
  Msgbox: {},
  ObjxTempl: { soon: true },
  Roller: {},
  Scale: {},
  Table: {},
  Tabview: {},
  Tileview: {},
  Radio: {},
  RadioGroup: {
    rootParentType: 'Radio',
  },
  SimpleGrid: {},
  Slider: {},
  Spinbox: {},
  Spinner: {},
  Select: {},
  Skeleton: {},
  SkeletonCircle: {},
  SkeletonText: {},
  Stack: {},
  Stat: {
    children: {
      StatGroup: {},
      Stat: {},
      StatLabel: {},
      StatNumber: {},
      StatHelpText: {},
      StatArrow: {},
    },
  },
  Switch: {},
  Tabs: {
    children: {
      Tabs: {},
      Tab: {},
      TabList: {},
      TabPanel: {},
      TabPanels: {},
    },
  },
  Tag: {},
  Text: {},
  Textarea: {},
  Window: {},
  Menu: {},
}

// Compatibility types may still occur in old serialized projects, but they
// are not registered ForgeUI widgets and must not be advertised to the
// Inspector, AI catalogue, Tray, or export capability surfaces.
export const futureUnregisteredWidgetTypes = new Set<ComponentType>([
  'Lottie',
  'ObjxTempl',
  'Editable',
])

export const componentsList: ComponentType[] = ([
  'Accordion',
  'AccordionIcon',
  'AccordionItem',
  'AccordionPanel',
  'Alert',
  'AlertDescription',
  'AlertIcon',
  'AlertTitle',
  'AnimImage',
  'Arc',
  'AspectRatio',
  'Avatar',
  'AvatarBadge',
  'AvatarGroup',
  'Badge',
  'Bar',
  'Box',
  'Breadcrumb',
  'BreadcrumbItem',
  'BreadcrumbLink',
  'Button',
  'InteractiveButton',
  'InteractiveLight',
  'InteractiveStatusIndicator',
  'InteractiveToggleSwitch',
  'InteractiveThreePositionToggleSwitch',
  'ButtonMatrix',
  'Calendar',
  'Canvas',
  'Center',
  'Chart',
  'Checkbox',
  'CircularProgress',
  'CloseButton',
  'Code',
  'Container',
  'Divider',
  'DashboardCard',
  'SensorTile',
  'RelayPanel',
  'PwmController',
  'TrendChart',
  'TrendChartPro',
  'AlarmPanel',
  'Editable',
  'Flex',
  'FormControl',
  'FormErrorMessage',
  'FormHelperText',
  'FormLabel',
  'Grid',
  'Heading',
  'Clock',
  'WiFi',
  'Highlight',
  'Icon',
  'IconButton',
  'Span',
  'Image',
  'ImageButton',
  'Input',
  'InputGroup',
  'InputLeftAddon',
  'InputLeftElement',
  'InputRightAddon',
  'InputRightElement',
  'Kbd',
  'Keyboard',
  'Led',
  'Line',
  'Link',
  'List',
  'ListIcon',
  'ListItem',
  'Lottie',
  'Menu',
  'Msgbox',
  'NumberInput',
  'ObjxTempl',
  'Progress',
  'QRCode',
  'Radio',
  'RadioGroup',
  'Roller',
  'Scale',
  'Select',
  'Slider',
  'Spinbox',
  'SimpleGrid',
  'Spinner',
  'Skeleton',
  'SkeletonCircle',
  'SkeletonText',
  'Stack',
  'Stat',
  'StatArrow',
  'StatGroup',
  'StatHelpText',
  'StatLabel',
  'StatNumber',
  'Switch',
  'Tab',
  'Table',
  'TabList',
  'TabPanel',
  'TabPanels',
  'Tabs',
  'Tabview',
  'Tag',
  'Text',
  'Textarea',
  'Tileview',
  'Window',
] as ComponentType[]).filter(type => !futureUnregisteredWidgetTypes.has(type))
