import React, { useMemo } from 'react'
import { Box, Flex, Grid, Stack, Text } from '@chakra-ui/react'
import { ForgeUIIOState, normalizeForgeUIIOMonitor, simulateForgeUIIOChannels } from '../ForgeUIIOMonitor'
import { ForgePreviewPalette, resolveForgeSemanticPalette } from './forgeThemeMap'

export const ForgeUIIOMonitorPreview = ({ component, palette }: { component: IComponent; palette: ForgePreviewPalette }) => {
  const model = normalizeForgeUIIOMonitor(component.props); const theme = resolveForgeSemanticPalette(palette)
  const channels = useMemo(() => simulateForgeUIIOChannels(model), [model])
  const colours: Record<ForgeUIIOState,string> = { off:model.offColour,on:model.onColour,active:model.activeColour,inactive:model.inactiveColour,fault:model.faultColour,disabled:model.disabledColour,unknown:model.unknownColour }
  const visible = channels.filter(channel => channel.visible && (model.includeDisabled || channel.state !== 'disabled') && (model.includeFaults || channel.state !== 'fault') && (model.includeInputs || channel.type !== 'digital-input') && (model.includeOutputs || !['digital-output','relay','pump','valve','motor','fan','solenoid'].includes(channel.type)))
  const row = (channel: typeof visible[number]) => <Flex data-testid={`io-${channel.id}`} key={channel.id} align="center" gap="8px" minW="0" p={model.displayMode === 'compact-grid' ? '4px' : '7px'} background={theme.surfaceSecondary} borderRadius={model.rounded ? '8px' : 0}><Box flex="none" width={`${model.indicatorSize}px`} height={`${model.indicatorSize}px`} borderRadius="50%" background={colours[channel.state]} boxShadow={`0 0 7px ${colours[channel.state]}55`} />{model.showLabels && <Box flex="1" minW="0"><Text fontSize="xs" fontWeight="700" noOfLines={1}>{channel.label}</Text>{model.displayMode !== 'compact-grid' && model.showStateText && <Text fontSize="10px" color={colours[channel.state]}>{channel.state.toUpperCase()}</Text>}</Box>}{model.showValues && channel.value && <Text fontSize="10px">{channel.value}</Text>}{model.showTimestamps && <Text fontSize="9px" color={theme.textSecondary}>{channel.timestamp}</Text>}</Flex>
  return <Flex data-testid="forgeui-io-monitor" direction="column" width="100%" height="100%" overflow="hidden" p="12px" gap="8px" color={theme.textPrimary} background={model.glassStyle ? `linear-gradient(155deg, ${theme.surface}, ${theme.surfaceSecondary})` : theme.surface} border="1px solid" borderColor={theme.surfaceBorder} borderRadius={model.rounded ? '12px' : 0} boxShadow={model.shadow ? '0 10px 24px rgba(0,0,0,.24)' : 'none'}><Flex justify="space-between"><Text fontWeight="700">{model.title}</Text><Text fontSize="xs" color={theme.textSecondary}>{visible.length} channels</Text></Flex>{model.displayMode === 'list' ? <Stack overflowY="auto" spacing="4px">{visible.map(row)}</Stack> : <Grid overflowY="auto" templateColumns={`repeat(${model.displayMode === 'compact-grid' ? 4 : 2}, minmax(0, 1fr))`} gap="5px">{visible.map(row)}</Grid>}</Flex>
}
